import type { LocalServicesFunnelConfig } from "@/app/templates/local-services/config.types";

// ─── GEO Pricing Config ───────────────────────────────────────────────────────
// scheduleRoute: pass "/" + slug + "/schedule" for affiliates, "/schedule" for god page

export function buildGeoPricingConfig(scheduleRoute: string, links: Record<string, string> = {}): LocalServicesFunnelConfig {
  return {
    brandName: "GEO by HeyPearl",
    brandTagline: "AI Visibility for Real Estate Agents",
    colorPrimary: "#E8185C",
    colorNavy: "#0F1E3A",
    colorLight: "#EDF0FA",
    colorBg: "#F7F8FC",
    funnelTag: "geo",
    scheduleRoute,
    pricingRoute: "",
    apiOptinRoute: "/api/optin",
    calendlyUrl: "https://calendly.com/hey-pearl/meet",
    heroHeadline: "",
    heroHeadlineAccent: "",
    heroSubheadline: "",
    heroPrimaryCtaLabel: "",
    heroStats: [],
    resultStats: [],
    painSectionLabel: "",
    painHeadline: "",
    painSubheadline: "",
    painCards: [],
    testimonials: [],
    services: [],
    steps: [],
    faqs: [],
    formHeadline: "",
    formSubheadline: "",
    formCtaLabel: "",
    scheduleHeadline: "",
    scheduleSubheadline: "",
    scheduleTestimonialQuote: "",
    scheduleTestimonialAuthor: "",
    scheduleCallItems: [],
    scheduleWhatHappens: [],
    founder: { initials: "", name: "", title: "", stats: [] },
    fomoEntries: [],
    fomoPopupLabel: "",

    pricingTiers: [
      {
        name: "Package 1",
        price: "$1,500",
        features: [
          "Content Management (FB, IG, YT, GBP)",
          "Blue Ocean Strategy (Hyperlocal positioning)",
          "AEO (Answer Engine Optimization)",
          "Keyword Targeting",
          "AI Visibility (GEO framework)",
          "Brand Kit Alignment",
          "Retargeting Setup and Management",
          "Lead Capture System",
          "Review Request Automation",
          "Blogs (2/month)",
        ],
        ctaLabel: links.starter ? "Get Started" : "Book a Call",
        ctaHref: links.starter ?? scheduleRoute,
      },
      {
        name: "Package 2",
        price: "$2,500",
        highlight: true,
        features: [
          "Everything in Package 1",
          "Newsletters (2/month)",
          "Website Schema Setup",
          "AI Avatar",
          "Platform Optimization (IG, TikTok, YT)",
          "Podcast Content",
          "Exclusivity",
          "Blogs (4/month)",
        ],
        ctaLabel: links.growth ? "Get Started" : "Book a Call",
        ctaHref: links.growth ?? scheduleRoute,
      },
      {
        name: "Package 3",
        price: "$3,500",
        features: [
          "Everything in Package 2",
          "V2 Listing Appointment System included",
          "Press Releases (2/month)",
          "Advanced Automations",
          "Blogs (8/month)",
          "Newsletters (4/month)",
        ],
        ctaLabel: links.pro ? "Get Started" : "Book a Call",
        ctaHref: links.pro ?? scheduleRoute,
      },
    ],

    pricingComparisonRows: [
      { feature: "Content Management (FB, IG, YT, GBP)", starter: true, growth: true, pro: true },
      { feature: "Blue Ocean Strategy (Hyperlocal positioning)", starter: true, growth: true, pro: true },
      { feature: "AEO (Answer Engine Optimization)", starter: true, growth: true, pro: true },
      { feature: "Keyword Targeting", starter: true, growth: true, pro: true },
      { feature: "AI Visibility (GEO framework)", starter: true, growth: true, pro: true },
      { feature: "Brand Kit Alignment", starter: true, growth: true, pro: true },
      { feature: "Retargeting Setup and Management", starter: true, growth: true, pro: true },
      { feature: "Lead Capture System", starter: true, growth: true, pro: true },
      { feature: "Review Request Automation", starter: true, growth: true, pro: true },
      { feature: "Blogs", starter: "2/mo", growth: "4/mo", pro: "8/mo" },
      { feature: "Newsletters", starter: false, growth: "2/mo", pro: "4/mo" },
      { feature: "Website Schema Setup", starter: false, growth: true, pro: true },
      { feature: "AI Avatar", starter: false, growth: true, pro: true },
      { feature: "Platform Optimization (IG, TikTok, YT)", starter: false, growth: true, pro: true },
      { feature: "Podcast Content", starter: false, growth: true, pro: true },
      { feature: "Exclusivity", starter: false, growth: true, pro: true },
      { feature: "Press Releases", starter: false, growth: false, pro: "2/mo" },
      { feature: "Advanced Automations", starter: false, growth: false, pro: true },
      { feature: "V2 Listing Appointment System", starter: false, growth: false, pro: true },
    ],
  };
}

// ─── V2 Pricing Config ────────────────────────────────────────────────────────
// Tiers show V2 alone vs V2 bundled with GEO to compound results

export function buildV2PricingConfig(scheduleRoute: string, links: Record<string, string> = {}): LocalServicesFunnelConfig {
  return {
    brandName: "V2 by HeyPearl",
    brandTagline: "Done-for-You Listing Appointment System",
    colorPrimary: "#16A34A",
    colorNavy: "#0F1E3A",
    colorLight: "#EDF0FA",
    colorBg: "#F7F8FC",
    funnelTag: "v2",
    scheduleRoute,
    pricingRoute: "",
    apiOptinRoute: "/api/optin",
    calendlyUrl: "https://calendly.com/hey-pearl/meet",
    heroHeadline: "",
    heroHeadlineAccent: "",
    heroSubheadline: "",
    heroPrimaryCtaLabel: "",
    heroStats: [],
    resultStats: [],
    painSectionLabel: "",
    painHeadline: "",
    painSubheadline: "",
    painCards: [],
    testimonials: [],
    services: [],
    steps: [],
    faqs: [],
    formHeadline: "",
    formSubheadline: "",
    formCtaLabel: "",
    scheduleHeadline: "",
    scheduleSubheadline: "",
    scheduleTestimonialQuote: "",
    scheduleTestimonialAuthor: "",
    scheduleCallItems: [],
    scheduleWhatHappens: [],
    founder: { initials: "", name: "", title: "", stats: [] },
    fomoEntries: [],
    fomoPopupLabel: "",

    pricingTiers: [
      {
        name: "V2 Only",
        price: "$1,500",
        features: [
          "Done-for-you listing appointment system",
          "Seller outreach email sequences",
          "Appointment booking automation",
          "Monthly performance report",
          "Market exclusivity (1 per city)",
        ],
        ctaLabel: links.standalone ? "Get Started" : "Book a Call",
        ctaHref: links.standalone ?? scheduleRoute,
      },
      {
        name: "V2 + GEO Starter",
        price: "$2,500",
        highlight: true,
        features: [
          "Everything in V2 Only",
          "Content Management (FB, IG, YT, GBP)",
          "AEO (Answer Engine Optimization)",
          "AI Visibility (GEO framework)",
          "Retargeting Setup and Management",
          "Lead Capture System",
          "Blogs (2/month)",
          "Compound your results",
        ],
        ctaLabel: links.bundle ? "Get Started" : "Book a Call",
        ctaHref: links.bundle ?? scheduleRoute,
      },
      {
        name: "Full Stack",
        price: "$3,500",
        features: [
          "Everything in V2 + GEO Starter",
          "Newsletters (2/month)",
          "Website Schema Setup",
          "AI Avatar",
          "Platform Optimization (IG, TikTok, YT)",
          "Podcast Content",
          "Exclusivity",
          "Press Releases (2/month)",
          "Advanced Automations",
        ],
        ctaLabel: links.fullstack ? "Get Started" : "Book a Call",
        ctaHref: links.fullstack ?? scheduleRoute,
      },
    ],

    pricingComparisonRows: [
      { feature: "Done-for-you appointment system", starter: true, growth: true, pro: true },
      { feature: "Seller outreach sequences", starter: true, growth: true, pro: true },
      { feature: "Appointment booking automation", starter: true, growth: true, pro: true },
      { feature: "Monthly performance report", starter: true, growth: true, pro: true },
      { feature: "Market exclusivity (1 per city)", starter: true, growth: true, pro: true },
      { feature: "Content Management (FB, IG, YT, GBP)", starter: false, growth: true, pro: true },
      { feature: "AEO (Answer Engine Optimization)", starter: false, growth: true, pro: true },
      { feature: "AI Visibility (GEO framework)", starter: false, growth: true, pro: true },
      { feature: "Retargeting Setup and Management", starter: false, growth: true, pro: true },
      { feature: "Lead Capture System", starter: false, growth: true, pro: true },
      { feature: "Blogs", starter: false, growth: "2/mo", pro: "8/mo" },
      { feature: "Newsletters", starter: false, growth: false, pro: "2/mo" },
      { feature: "Website Schema Setup", starter: false, growth: false, pro: true },
      { feature: "AI Avatar", starter: false, growth: false, pro: true },
      { feature: "Platform Optimization (IG, TikTok, YT)", starter: false, growth: false, pro: true },
      { feature: "Podcast Content", starter: false, growth: false, pro: true },
      { feature: "Exclusivity", starter: false, growth: false, pro: true },
      { feature: "Press Releases", starter: false, growth: false, pro: "2/mo" },
      { feature: "Advanced Automations", starter: false, growth: false, pro: true },
    ],
  };
}
